@startuml ApacheScheme

node MKRFox1200 {
	[Arduino] -u-> SigFox
	DHT - [Arduino]
}

database SigFox as SigFoxCloud {
	SigFox -> Antenne
	Antenne --> [SRV]
}

cloud Internet {
	database Infomaniak {
		[SRV] -> HTTP
		HTTP - [Apache]
		[Apache] <--> [MySql]
	}
}

@enduml

@startuml DBScheme
entity Measure {
	id: Bigint
	temperature : Float
	humidity : Float
	measure_time : Timestamp
	sequence_number: Int
	device: Bigint
}

entity Device {
	id: Bigint
	{field} device_id: Varchar(6)
}

Measure "*" - " 0..1" Device
@enduml
