@startuml MailScheme

node MKRFox1200 {
	[Arduino]
	DHT - [Arduino]
	[Arduino] --> SigFox
}

database SigFox as SigFoxCloud {
	SigFox -> Antenne
	Antenne - [SRV]
}


cloud Internet {
	database Infomaniak {
		[Serveur SMTP]
	}
}

[SRV] -> [Serveur SMTP]
@enduml
