@startuml MailScheme

node MKRFox1200 {
	port SigFox
	[Arduino] -> SigFox
	DHT - [Arduino]
}

cloud SigFox as SigFoxCloud {
	portin Antenne
	SigFox -> Antenne
	Antenne -> [SRV]
}

cloud Infomaniak {
	frame "Web Host" {
		SRV-->HTTP
		HTTP - [Apache]
	}

	[Apache] -> [Serveur SMTP]: SMTP
}

@enduml
